    global Atts;
    global Gradient;
    global LSatt;
    global LinkSize;
    global Mfull;
    global Obs;     % Observation
    global Op;
    global Ufull;
    global file_AttEstimatedtime;
    global file_linkIncidence;
    global file_observations;
    global file_turnAngles;
    global incidenceFull; 
    global isLinkSizeInclusive;
    global maxstates;
    global nbobs;  
    global incidenceFull;
    global EstimatedTime;
    global TurnAngles;
    global LeftTurn;
    global Uturn;    
    global LinkSize;
    global isFixedUturn;
    isLinkSizeInclusive;